spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      password: ${SPRING_REDIS_PASSWORD}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

pdfgen:
  api-key: ${PDFGEN_API_KEY}
  compiler:
    host: ${PDFGEN_COMPILER_HOST}
    port: ${PDFGEN_COMPILER_PORT:50051}
  rabbit:
    enabled: ${PDFGEN_RABBIT_ENABLED:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
      show-components: never
      group:
        readiness:
          include: db,redis,rabbit,compiler
  health:
    rabbit:
      enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
