apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pdfgen

resources:
  - ../../base/namespace.yaml
  - ../../base/rust-compiler.yaml
  - ../../base/java-api.yaml
  - ../../base/network-policy.yaml

patches:
  - target:
      kind: Deployment
      name: java-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: rust-compiler
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
